### ISSUE TITLE
Add `vite dev` to scripts

### ISSUE THREAD

**Issue by WebMechanic** [originjs/webpack-to-vite#107]
### Is your feature request related to a problem? Please describe.

After migratioin three vite scripts are aded to `package-json`
```json
"serve-vite": "vite",
"build-vite": "vite build",
"preview-vite": "vite preview"
```
a call to `vite dev` is missing. 

### Describe the solution you'd like

Pleasa also include
```json
"dev-vite": "vite dev",
```

I ran several migartions and always had to add this line.

**Comment by Chieffo2021** [comment]
I think they are the same. FYI https://vitejs.dev/guide/#command-line-interface
<img width="783" alt="image" src="https://user-images.githubusercontent.com/85914490/194762158-3afb3cd5-dd3d-4b9d-9d39-4c91c74ec66f.png">

**Comment by WebMechanic** [comment]
thanks!
interesting, must be eithe a new Vite 3 feature then or I'm confusing this with (old?) vue-cli scripts + webpack where "serve" required a previous run of `build` to serve files...
looks like this is what `preview` does ...
