### ISSUE TITLE
TypeError: At least one of max, maxSize, or ttl is required

### ISSUE THREAD

**Issue by canvascat** [originjs/webpack-to-vite#93]
### Versions

- webpack-to-vite: 1.1.0
- node: v17.3.1

### Steps to reproduce

![image](https://user-images.githubusercontent.com/31235016/162652332-916679b8-5bfe-4e94-ab5a-09bf3a7da6ba.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/31235016/162652107-ab0ae436-b7b4-4508-9f3f-286373f744b7.png)

**Comment by MomchilGorchev** [comment]
Hello there, I'm having the same issue:

node: v16.14.2
npm: v8.5.0

**Comment by mrhammadasif** [comment]
Facing same issue

```
❯ node -v
v16.13.1
❯ npm -v
8.1.2
```
